namespace Delivery
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.ps = new NPlot.Windows.PlotSurface2D();
            this.tbExpr = new System.Windows.Forms.TextBox();
            this.tbN = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.tbTMax = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.dgvTQ = new System.Windows.Forms.DataGridView();
            this.t = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Q = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.tbCDl = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.tbCSt = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            this.tbQSum = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.tbCDlSum = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.tbCStSum = new System.Windows.Forms.TextBox();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.calcToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.doCalcToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.rbAn = new System.Windows.Forms.RadioButton();
            this.rbTb = new System.Windows.Forms.RadioButton();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.dgvFn = new System.Windows.Forms.DataGridView();
            this.exitToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.saveRepToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveFileDialog1 = new System.Windows.Forms.SaveFileDialog();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTQ)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvFn)).BeginInit();
            this.SuspendLayout();
            // 
            // ps
            // 
            this.ps.AutoScaleAutoGeneratedAxes = false;
            this.ps.AutoScaleTitle = false;
            this.ps.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.ps.DateTimeToolTip = false;
            this.ps.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ps.Legend = null;
            this.ps.LegendZOrder = -1;
            this.ps.Location = new System.Drawing.Point(0, 0);
            this.ps.Name = "ps";
            this.ps.RightMenu = null;
            this.ps.ShowCoordinates = true;
            this.ps.Size = new System.Drawing.Size(337, 119);
            this.ps.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.ps.TabIndex = 0;
            this.ps.Text = "plotSurface2D1";
            this.ps.Title = "";
            this.ps.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.ps.XAxis1 = null;
            this.ps.XAxis2 = null;
            this.ps.YAxis1 = null;
            this.ps.YAxis2 = null;
            // 
            // tbExpr
            // 
            this.tbExpr.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbExpr.Location = new System.Drawing.Point(6, 42);
            this.tbExpr.Name = "tbExpr";
            this.tbExpr.Size = new System.Drawing.Size(202, 20);
            this.tbExpr.TabIndex = 3;
            // 
            // tbN
            // 
            this.tbN.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbN.Location = new System.Drawing.Point(6, 32);
            this.tbN.Name = "tbN";
            this.tbN.Size = new System.Drawing.Size(202, 20);
            this.tbN.TabIndex = 5;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(3, 16);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(119, 13);
            this.label2.TabIndex = 4;
            this.label2.Text = "Количество поставок:";
            // 
            // tbTMax
            // 
            this.tbTMax.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbTMax.Location = new System.Drawing.Point(6, 71);
            this.tbTMax.Name = "tbTMax";
            this.tbTMax.Size = new System.Drawing.Size(202, 20);
            this.tbTMax.TabIndex = 7;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(3, 55);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(48, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "Период:";
            // 
            // dgvTQ
            // 
            this.dgvTQ.AllowUserToAddRows = false;
            this.dgvTQ.AllowUserToDeleteRows = false;
            this.dgvTQ.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.dgvTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTQ.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvTQ.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.t,
            this.Q});
            this.dgvTQ.Location = new System.Drawing.Point(3, 130);
            this.dgvTQ.Name = "dgvTQ";
            this.dgvTQ.RowHeadersVisible = false;
            this.dgvTQ.Size = new System.Drawing.Size(331, 95);
            this.dgvTQ.TabIndex = 8;
            // 
            // t
            // 
            this.t.HeaderText = "t";
            this.t.Name = "t";
            this.t.ReadOnly = true;
            // 
            // Q
            // 
            this.Q.HeaderText = "Q";
            this.Q.Name = "Q";
            this.Q.ReadOnly = true;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 24);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.groupBox2);
            this.splitContainer1.Panel1.Controls.Add(this.groupBox1);
            this.splitContainer1.Panel1MinSize = 221;
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.splitContainer2);
            this.splitContainer1.Size = new System.Drawing.Size(562, 354);
            this.splitContainer1.SplitterDistance = 221;
            this.splitContainer1.TabIndex = 9;
            // 
            // tbCDl
            // 
            this.tbCDl.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbCDl.Location = new System.Drawing.Point(6, 149);
            this.tbCDl.Name = "tbCDl";
            this.tbCDl.Size = new System.Drawing.Size(202, 20);
            this.tbCDl.TabIndex = 11;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(3, 133);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(115, 13);
            this.label5.TabIndex = 10;
            this.label5.Text = "Стоимость доставки:";
            // 
            // tbCSt
            // 
            this.tbCSt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbCSt.Location = new System.Drawing.Point(6, 110);
            this.tbCSt.Name = "tbCSt";
            this.tbCSt.Size = new System.Drawing.Size(202, 20);
            this.tbCSt.TabIndex = 9;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(3, 93);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(115, 13);
            this.label4.TabIndex = 8;
            this.label4.Text = "Стоимость хранения:";
            // 
            // splitContainer2
            // 
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.Location = new System.Drawing.Point(0, 0);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer2.Panel1
            // 
            this.splitContainer2.Panel1.Controls.Add(this.ps);
            // 
            // splitContainer2.Panel2
            // 
            this.splitContainer2.Panel2.Controls.Add(this.tbQSum);
            this.splitContainer2.Panel2.Controls.Add(this.label8);
            this.splitContainer2.Panel2.Controls.Add(this.tbCDlSum);
            this.splitContainer2.Panel2.Controls.Add(this.dgvTQ);
            this.splitContainer2.Panel2.Controls.Add(this.label7);
            this.splitContainer2.Panel2.Controls.Add(this.label6);
            this.splitContainer2.Panel2.Controls.Add(this.tbCStSum);
            this.splitContainer2.Size = new System.Drawing.Size(337, 354);
            this.splitContainer2.SplitterDistance = 119;
            this.splitContainer2.TabIndex = 0;
            // 
            // tbQSum
            // 
            this.tbQSum.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbQSum.Enabled = false;
            this.tbQSum.Location = new System.Drawing.Point(11, 104);
            this.tbQSum.Name = "tbQSum";
            this.tbQSum.Size = new System.Drawing.Size(314, 20);
            this.tbQSum.TabIndex = 17;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(11, 88);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(131, 13);
            this.label8.TabIndex = 16;
            this.label8.Text = "Общий объем поставок:";
            // 
            // tbCDlSum
            // 
            this.tbCDlSum.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbCDlSum.Enabled = false;
            this.tbCDlSum.Location = new System.Drawing.Point(11, 65);
            this.tbCDlSum.Name = "tbCDlSum";
            this.tbCDlSum.Size = new System.Drawing.Size(314, 20);
            this.tbCDlSum.TabIndex = 15;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(11, 49);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(179, 13);
            this.label7.TabIndex = 14;
            this.label7.Text = "Суммарные затраты на доставку:";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(8, 10);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(180, 13);
            this.label6.TabIndex = 12;
            this.label6.Text = "Суммарные затраты на хранение:";
            // 
            // tbCStSum
            // 
            this.tbCStSum.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tbCStSum.Enabled = false;
            this.tbCStSum.Location = new System.Drawing.Point(11, 26);
            this.tbCStSum.Name = "tbCStSum";
            this.tbCStSum.Size = new System.Drawing.Size(314, 20);
            this.tbCStSum.TabIndex = 13;
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.exitToolStripMenuItem,
            this.calcToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(562, 24);
            this.menuStrip1.TabIndex = 10;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.saveRepToolStripMenuItem,
            this.exitToolStripMenuItem1});
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(45, 20);
            this.exitToolStripMenuItem.Text = "Файл";
            // 
            // calcToolStripMenuItem
            // 
            this.calcToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.doCalcToolStripMenuItem});
            this.calcToolStripMenuItem.Name = "calcToolStripMenuItem";
            this.calcToolStripMenuItem.Size = new System.Drawing.Size(86, 20);
            this.calcToolStripMenuItem.Text = "Оптимизация";
            // 
            // doCalcToolStripMenuItem
            // 
            this.doCalcToolStripMenuItem.Name = "doCalcToolStripMenuItem";
            this.doCalcToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.doCalcToolStripMenuItem.Text = "Выполнить";
            this.doCalcToolStripMenuItem.Click += new System.EventHandler(this.doCalcToolStripMenuItem_Click);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Controls.Add(this.dgvFn);
            this.groupBox1.Controls.Add(this.rbTb);
            this.groupBox1.Controls.Add(this.rbAn);
            this.groupBox1.Controls.Add(this.tbExpr);
            this.groupBox1.Location = new System.Drawing.Point(4, 189);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(214, 162);
            this.groupBox1.TabIndex = 12;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Функция потребления материала V(t)";
            // 
            // rbAn
            // 
            this.rbAn.AutoSize = true;
            this.rbAn.Checked = true;
            this.rbAn.Location = new System.Drawing.Point(6, 19);
            this.rbAn.Name = "rbAn";
            this.rbAn.Size = new System.Drawing.Size(141, 17);
            this.rbAn.TabIndex = 4;
            this.rbAn.TabStop = true;
            this.rbAn.Text = "Задание аналитически";
            this.rbAn.UseVisualStyleBackColor = true;
            // 
            // rbTb
            // 
            this.rbTb.AutoSize = true;
            this.rbTb.Location = new System.Drawing.Point(6, 68);
            this.rbTb.Name = "rbTb";
            this.rbTb.Size = new System.Drawing.Size(122, 17);
            this.rbTb.TabIndex = 5;
            this.rbTb.Text = "Задание по точкам";
            this.rbTb.UseVisualStyleBackColor = true;
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.tbCDl);
            this.groupBox2.Controls.Add(this.tbN);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.tbCSt);
            this.groupBox2.Controls.Add(this.tbTMax);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Location = new System.Drawing.Point(4, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(214, 180);
            this.groupBox2.TabIndex = 13;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Данные";
            // 
            // dgvFn
            // 
            this.dgvFn.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.dgvFn.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvFn.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvFn.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dataGridViewTextBoxColumn1,
            this.dataGridViewTextBoxColumn2});
            this.dgvFn.Location = new System.Drawing.Point(6, 91);
            this.dgvFn.Name = "dgvFn";
            this.dgvFn.RowHeadersVisible = false;
            this.dgvFn.Size = new System.Drawing.Size(202, 65);
            this.dgvFn.TabIndex = 9;
            // 
            // exitToolStripMenuItem1
            // 
            this.exitToolStripMenuItem1.Name = "exitToolStripMenuItem1";
            this.exitToolStripMenuItem1.Size = new System.Drawing.Size(173, 22);
            this.exitToolStripMenuItem1.Text = "Выход";
            this.exitToolStripMenuItem1.Click += new System.EventHandler(this.exitToolStripMenuItem1_Click);
            // 
            // dataGridViewTextBoxColumn1
            // 
            this.dataGridViewTextBoxColumn1.HeaderText = "t";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            // 
            // dataGridViewTextBoxColumn2
            // 
            this.dataGridViewTextBoxColumn2.HeaderText = "V";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            // 
            // saveRepToolStripMenuItem
            // 
            this.saveRepToolStripMenuItem.Name = "saveRepToolStripMenuItem";
            this.saveRepToolStripMenuItem.Size = new System.Drawing.Size(173, 22);
            this.saveRepToolStripMenuItem.Text = "Сохранить отчет";
            this.saveRepToolStripMenuItem.Click += new System.EventHandler(this.saveRepToolStripMenuItem_Click);
            // 
            // saveFileDialog1
            // 
            this.saveFileDialog1.FileName = "Отчет1.txt";
            this.saveFileDialog1.Filter = "Текстовые файлы|*.txt";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(562, 378);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.MinimumSize = new System.Drawing.Size(570, 412);
            this.Name = "Form1";
            this.Text = "Однопродуктовая детерм. задача управления запасами: (n) - политика";
            ((System.ComponentModel.ISupportInitialize)(this.dgvTQ)).EndInit();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel2.ResumeLayout(false);
            this.splitContainer2.Panel2.PerformLayout();
            this.splitContainer2.ResumeLayout(false);
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvFn)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private NPlot.Windows.PlotSurface2D ps;
        private System.Windows.Forms.TextBox tbExpr;
        private System.Windows.Forms.TextBox tbN;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox tbTMax;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.DataGridView dgvTQ;
        private System.Windows.Forms.DataGridViewTextBoxColumn t;
        private System.Windows.Forms.DataGridViewTextBoxColumn Q;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.SplitContainer splitContainer2;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.TextBox tbCDl;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox tbCSt;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox tbCDlSum;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox tbCStSum;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox tbQSum;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.ToolStripMenuItem calcToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem doCalcToolStripMenuItem;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton rbTb;
        private System.Windows.Forms.RadioButton rbAn;
        private System.Windows.Forms.DataGridView dgvFn;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem saveRepToolStripMenuItem;
        private System.Windows.Forms.SaveFileDialog saveFileDialog1;
    }
}

